<?php $uniqId = substr(md5(time()), 5, 15); ?>
<form id="promo-form-<?php echo $uniqId; ?>" class="binded-plugin prefix_3 suffix_3 grid_6 mt50px" action="<?php echo trim($this->websiteUrl, '/') . $this->url(); ?>" method="POST">
    <fieldset class="background">
        <legend class="background large"><?php echo $this->translate('Set all products on sale'); ?>:</legend>
        <p>
            <label class="mt5px grid_5 alpha" for="promo-price"><?php echo $this->translate('Sale discount (%)'); ?>:</label>
            <?php echo $this->formText('promo-price', null, array('class' => 'grid_4 omega')); ?>
            <label class="mt5px labeled grid_3 text-center omega">
                <span><?php echo $this->translate('Time');?></span><i class="tooltip info ticon-question-sign icon16 mb5px ml3"
                                                                      title="<?php echo $this->translate('Sales time depends on your local server time settings');?>"></i>
            </label>
        </p>
        <p>
            <label class="mt5px grid_5 alpha" for="promo-from"><?php echo $this->translate('Starting date'); ?>:</label>
            <label class="labeled icon right grid_4 omega">
                <?php echo $this->formText('promo-from'); ?>
                <i class="ticon-calendar icon16"></i>
            </label>
            <label class="mt5px labeled text-center grid_3">
                <span>00.00</span>
            </label>
        </p>
        <p>
            <label class="mt5px grid_5 alpha" for="promo-due"><?php echo $this->translate('Expiry date'); ?>:</label>
            <label class="labeled icon right grid_4 omega">
                <?php echo $this->formText('promo-due'); ?>
                <i class="ticon-calendar icon16"></i>
            </label>
            <label class="mt5px labeled text-center grid_3">
                <span>23.59</span>
            </label>
        </p>
        <?php echo $this->formButton(
            'promo-dismiss',
            $this->translate('Dismiss all promo prices'),
            array('class' => 'btn error fl-left', 'type' => 'submit')
        ); ?>
        <input type="hidden" name="<?php echo Tools_System_Tools::CSRF_SECURE_TOKEN;?>" value="<?php echo $this->secureToken;?>" />
        <?php echo $this->formButton('promo-save', $this->translate('Apply to all products'), array('type' => 'submit', 'class' => 'btn icon-checkmark-3')); ?>
    </fieldset>
</form>
<form id="dismiss-promo" class="binded-plugin" action="<?php echo trim($this->websiteUrl, '/') . $this->url() . '/dismiss/1'; ?>" method="POST">
    <input type="hidden" name="<?php echo Tools_System_Tools::CSRF_SECURE_TOKEN;?>" value="<?php echo $this->secureToken;?>" />
</form>
<script type="text/javascript">
    $(function(){
        if(window.jQuery && jQuery.ui){
            var container = $('#promo-form-<?php echo $uniqId;?>');
            $('#promo-price-unit', container).text($('#currency-unit').text());
            $('#promo-from', container).datepicker({
                dateFormat  : 'dd-M-yy',
                changeMonth : true,
                changeYear  : true,
                yearRange   : "c:c+10",
                onSelect    : function(selectedDate){
                    $('#promo-due', container).datepicker("option", "minDate", selectedDate);
                }
            });
            $('#promo-due', container).datepicker({
                dateFormat  : 'dd-M-yy',
                defaultDate : "+1w",
                changeMonth : true,
                changeYear  : true,
                yearRange   : "c:c+10",
                onSelect    : function(selectedDate){
                    $('#promo-from', container).datepicker("option", "maxDate", selectedDate);
                }
            });
        }

        $('#promo-dismiss').on('click', function(e){
            e.preventDefault();
            $("#dismiss-promo").submit();
        });
    });
</script>